<?php

$ch = curl_init();
ob_start();
curl_setopt($ch, CURLOPT_URL, 'https://integration.sms.to/component_bulk_sms/manifest.json');
$response = curl_exec($ch);
curl_close($ch);
$response = ob_get_clean();
$manifest = json_decode($response, true);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl(); // to get Base Url
$VITE_ROUTE_PARAMS =  $url . "rest/V1/smsto-sms/params";
$VITE_ROUTE_SMSTO =  $url . "rest/V1/smsto-sms/callsmsto";
?>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <script type="module" crossorigin src="https://integration.sms.to/component_bulk_sms/<?= $manifest['src/main.ts']['file']; ?>"></script>
    <link rel="stylesheet" href="https://integration.sms.to/component_bulk_sms/<?= $manifest['src/main.ts']['css'][0]; ?>" />
</head>

<body>
    <div id="app_smsto" data-getParams="<?= $VITE_ROUTE_PARAMS; ?>" data-callSmsto="<?= $VITE_ROUTE_SMSTO; ?>" />
</body>
